typography_spectrum: 0.916678280569613
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7369904017541558
  lightness: 0.07827172242105007
  saturation: 0.2725580653641373
  rhythmicContrast: 0.14294088422320783
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5281130312941968
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alex Thebez
  email: alex@lint-roller.com
  url: www.alexthebez.com
name: wearelintroller
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: WEARELINTROLLER
description: Lintroller Studio
purpose: []
